version: '2'

services:
    influx:
        image: influxdb
        volumes:
            - influx-data:/data

    grafana:
        links:
            - influx:influx
        image: grafana/grafana
        ports:
            - "3000:3000"

    mosquitto:
        image: eclipse-mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"

volumes:
    influx-data:
        driver: local
